### ISSUE TITLE
не запускается расчет из h5 файла

### ISSUE THREAD

**Issue by dumbman** [epicf/ef_python#3]
ab@ab-work:~/ef_python/examples/single_particle_in_magnetic_field$ python3 ../../main.py long_simulation_0000000.h5 
Traceback (most recent call last):
  File "../../main.py", line 73, in <module>
    main()
  File "../../main.py", line 18, in main
    dom, continue_from_h5 = construct_domain( config_or_h5_file )
  File "../../main.py", line 36, in construct_domain
    extract_filename_prefix_and_suffix_from_h5filename( config_or_h5_file )     
  File "../../main.py", line 60, in extract_filename_prefix_and_suffix_from_h5filename
    if len( match.group ) == 1:
TypeError: object of type 'builtin_function_or_method' has no len()

**Comment by noooway** [comment]
Поправил некоторые вещи; теперь считается. По-крайней мере в примере с ribbon_beam_contour.
Думаю, надо сделать отдельный пример для теста перезапуска из фаила.
Поставить в конфиге все возможные секции. 
Только непонятно, как сравнить результаты перезапущенного варианта с расчетом из конфига.

**Comment by dumbman** [comment]
Заявку РФФИ поддержали

noooway писал 2018-03-16 20:50:

**Comment by dumbman** [comment]
ab@ab-work:~/ef_python/examples/single_particle_in_magnetic_field$ python3 ../../main.py long_simulation_0000500.h5
Extracted h5 prefix and suffix: long_simulation_ .h5
Traceback (most recent call last):
  File "../../main.py", line 73, in <module>
    main()
  File "../../main.py", line 18, in main
    dom, continue_from_h5 = construct_domain( config_or_h5_file )
  File "../../main.py", line 37, in construct_domain
    dom = Domain.init_from_h5( h5file )
  File "/home/ab/ef_python/Domain.py", line 52, in init_from_h5
    h5file["/External_fields"] )
  File "/home/ab/ef_python/ExternalFieldsManager.py", line 36, in init_from_h5
    self.parse_hdf5_external_field( current_field_grpid )
NameError: name 'self' is not defined

**Comment by dumbman** [comment]
ab@ab-work:~/ef_python/examples/single_particle_in_magnetic_field$ python3 ../../main.py long_simulation_0000200.h5 
Extracted h5 prefix and suffix: long_simulation_ .h5
Traceback (most recent call last):
  File "../../main.py", line 73, in <module>
    main()
  File "../../main.py", line 18, in main
    dom, continue_from_h5 = construct_domain( config_or_h5_file )
  File "../../main.py", line 37, in construct_domain
    dom = Domain.init_from_h5( h5file )
  File "/home/ab/ef_python/Domain.py", line 52, in init_from_h5
    h5file["/External_fields"] )
  File "/home/ab/ef_python/ExternalFieldsManager.py", line 36, in init_from_h5
    self.parse_hdf5_external_field( current_field_grpid )
NameError: name 'self' is not defined

**Comment by noooway** [comment]
Поправил пару вещей. 
Этот пример перезапускается.

**Comment by dumbman** [comment]
Да работает
